### ISSUE TITLE
Type definitions are wrong, so errors while compilation process

### ISSUE THREAD

**Issue by FriOne** [flauc/ng2-simple-components#1]
Please, provide correct type definitions. Or give an opportunity to merge them with own custom definitions at least. I mean `Property 'withComp' does not exist on type 'ModalService'.`

Thanks for components! I use one in my project, but these errors make me sad. :)

**Comment by flauc** [comment]
Hi @FriOne 

This is still a very early work in progress, especially the ModalModule. I'm working on getting the project in to a usable state, i'm sorry it isn't there yet. 

Also if you use the Modal in your project you should know it doesn't work with RC6 the `createComponentAsync()` method of the compiler was depreciated. 

I'll do a lot of work on the library over the weekend and hopefully this will get resolved a long with the .d.ts files.

**Comment by FriOne** [comment]
I just in a process of updating to RC6 :)) Ok, I revert then back to RC5..
Thanks, I will try to help you if I have some time.

**Comment by flauc** [comment]
That's great to hear. Thank you for the effort :+1: 

By the way i will likely update modals to RC6 this evening

**Comment by flauc** [comment]
Hi again @FriOne,

I think this new update should fix the typings issues. I think i found a really good way of automatically generating the typings in a way that plays nice with system.js and webpack. 

Please let me know if you still get the error.

**Comment by FriOne** [comment]
Unfortunally, now I have other errors :) `Duplicate identifier 'OnInit'.`
Also, what is `MyModal` here `this._modal.createWithModal(MyModal, MyComponent);`?

**Comment by FriOne** [comment]
You have nice demo now! :+1:  But where is modal demo? :)
